#cloud-config
# https://ubuntu.com/server/docs/install/autoinstall
# https://habr.com/ru/articles/813835/
# https://linuxconfig.org/how-to-write-and-perform-ubuntu-unattended-installations-with-autoinstall
# validate it:
# sudo cloud-init schema --config-file autoinstall.yaml
# TBD
autoinstall:
  version: 1
package_update: true
package_upgrade: true
