---
- name: Prepare role variables
  import_tasks: 00.prepare.yml

- name: Install packages
  import_tasks: 01.packages.yml

- name: Copy static
  import_tasks: 02.static-files.yml

- name: Install chrome
  import_tasks: 03.chrome.yml

- name: Install sdkman
  import_tasks: 04.sdkman.yml

- name: Configure XFCE
  import_tasks: 05.xfce.yml

- name: Install Intellij
  import_tasks: 06.intellij.yml

- name: Install docker
  import_tasks: 07.docker.yml

- name: Install java
  import_tasks: 08.java.yml

- name: Install ruby
  import_tasks: 09.ruby.yml

- name: Install python
  import_tasks: 10.python.yml

- name: Install node
  import_tasks: 11.node.yml

- name: configure ssh
  import_tasks: 12.ssh.yml

- name: configure bash-git-prompt
  import_tasks: 13.bash-git-prompt.yml

- name: Install postman
  import_tasks: 14.postman.yml

- name: Configure unlimited Bash history
  import_tasks: 15.bash-history.yml

- name: Configure Acer Swift 3
  ansible.builtin.import_tasks: hardware/acer-swift3.yml
  when: is_swift3

- name: Ceanup
  import_tasks: 99.cleanup.yml
