---
- name: Prepare role variables
  import_tasks: 00.prepare.yml

- name: Install packages
  import_tasks: 01.packages.yml

- name: Install chrome
  import_tasks: 02.chrome.yml

- name: Install postman
  import_tasks: 03.postman.yml

- name: Install sdkman
  import_tasks: 04.sdkman.yml
