---
- name: Configure Swift 3 AVS audio
  ansible.builtin.import_tasks: acer-swift3/audio.yml
  when: swift3_audio_enabled | bool

- name: Configure Swift 3 hibernate
  ansible.builtin.import_tasks: acer-swift3/hibernate-dracut.yml
  when: swift3_hibernate_enabled | bool
